export const memeData = [
  { id: "aybabtu", name: "All Your Base Are Belong To Us", bornYear: 2000, diedYear: 2004, color: "#00ff33", text: "CATS: ALL YOUR BASE ARE BELONG TO US", imageUrl: "https://i.imgflip.com/bzfox.jpg" },
  { id: "dancing_baby", name: "Dancing Baby", bornYear: 2000, diedYear: 2003, color: "#ffccaa", text: "OOGA CHAKA DANCING BABY", imageUrl: "https://i.imgflip.com/7gxla.jpg" },
  { id: "pbjt", name: "Peanut Butter Jelly Time", bornYear: 2002, diedYear: 2006, color: "#ffff00", text: "IT'S PEANUT BUTTER JELLY TIME!", imageUrl: "https://i.imgflip.com/1r1bep.jpg" },
  { id: "badgers", name: "Badger Badger Badger", bornYear: 2003, diedYear: 2006, color: "#bb9966", text: "BADGER BADGER BADGER MUSHROOM", imageUrl: "https://i.imgflip.com/2juuh.jpg" },
  { id: "orly", name: "O RLY?", bornYear: 2003, diedYear: 2007, color: "#ffffff", text: "O RLY? YA RLY! NO WAI!", imageUrl: "https://i.imgflip.com/7cxyr.jpg" },
  { id: "numanuma", name: "Numa Numa", bornYear: 2004, diedYear: 2008, color: "#4477ff", text: "MAI-A-HEE MAI-A-HOO", imageUrl: "https://i.imgflip.com/1blo0w.jpg" },
  { id: "pepe", name: "Pepe the Frog", bornYear: 2005, diedYear: 2026, color: "#33cc33", text: "FEELS GOOD MAN", imageUrl: "https://i.imgflip.com/lntct.jpg" },
  { id: "loituma", name: "Loituma Girl (Ievan Polkka)", bornYear: 2006, diedYear: 2008, color: "#ff99cc", text: "ARATSATSAY YA RI RI RABI RABI", imageUrl: "https://i.imgflip.com/4l4fsr.jpg" },
  { id: "rickroll", name: "Rickroll (Never Gonna Give You Up)", bornYear: 2007, diedYear: 2026, color: "#cc6633", text: "NEVER GONNA GIVE YOU UP", imageUrl: "https://i.imgflip.com/sfc8j.jpg" },
  { id: "chocolaterain", name: "Chocolate Rain", bornYear: 2007, diedYear: 2009, color: "#5c3a21", text: "CHOCOLATE RAIN", imageUrl: "https://i.imgflip.com/co8h4.jpg" },
  { id: "keyboardcat", name: "Keyboard Cat", bornYear: 2007, diedYear: 2012, color: "#ff9900", text: "PLAY HIM OFF, KEYBOARD CAT", imageUrl: "https://i.imgflip.com/brsab.jpg" },
  { id: "dramatic_chipmunk", name: "Dramatic Chipmunk", bornYear: 2007, diedYear: 2010, color: "#8b5a2b", text: "*DUN DUN DUNNN*", imageUrl: "https://i.imgflip.com/90lsp.jpg" },
  { id: "ragecomics", name: "Rage Comics", bornYear: 2008, diedYear: 2015, color: "#dddddd", text: "FUUUUUUU- / FFFUUUUU", imageUrl: "https://i.imgflip.com/fzoe8.jpg" },
  { id: "trololo", name: "Trololo Man", bornYear: 2009, diedYear: 2012, color: "#ffcc00", text: "TROLOLOLOLOLO", imageUrl: "https://i.imgflip.com/3ojlre.jpg" },
  { id: "double_rainbow", name: "Double Rainbow", bornYear: 2010, diedYear: 2013, color: "#ff33aa", text: "SO INTENSE! WHAT DOES IT MEAN?", imageUrl: "https://i.imgflip.com/4djg3.jpg" },
  { id: "bed_intruder", name: "Bed Intruder (Antoine Dodson)", bornYear: 2010, diedYear: 2012, color: "#ff2222", text: "HIDE YOUR KIDS, HIDE YOUR WIFE", imageUrl: "https://i.imgflip.com/5elt0.jpg" },
  { id: "friday", name: "Friday (Rebecca Black)", bornYear: 2011, diedYear: 2012, color: "#88ccff", text: "IT'S FRIDAY, FRIDAY, GETTING DOWN", imageUrl: "https://i.imgflip.com/53zbc.jpg" },
  { id: "nyancat", name: "Nyan Cat", bornYear: 2011, diedYear: 2018, color: "#ff3399", text: "NYAN NYAN NYAN NYAN", imageUrl: "https://i.imgflip.com/atevl.jpg" },
  { id: "honeybadger", name: "Honey Badger", bornYear: 2011, diedYear: 2014, color: "#aa8866", text: "HONEY BADGER DON'T CARE", imageUrl: "https://i.imgflip.com/2juuh.jpg" },
  { id: "planking", name: "Planking", bornYear: 2011, diedYear: 2012, color: "#77aa77", text: "PLANKING EVERYWHERE", imageUrl: "https://i.imgflip.com/3ahsn1.jpg" },
  { id: "grumpycat", name: "Grumpy Cat", bornYear: 2012, diedYear: 2019, color: "#ccaabb", text: "I HAD FUN ONCE. IT WAS AWFUL.", imageUrl: "https://i.imgflip.com/8p0a.jpg" },
  { id: "gangnam", name: "Gangnam Style", bornYear: 2012, diedYear: 2015, color: "#2244ff", text: "OPPA GANGNAM STYLE", imageUrl: "https://i.imgflip.com/40uy.jpg" },
  { id: "overly_attached", name: "Overly Attached Girlfriend", bornYear: 2012, diedYear: 2015, color: "#ff88aa", text: "I'M WATCHING YOU", imageUrl: "https://i.imgflip.com/25w8.jpg" },
  { id: "ermahgerd", name: "Ermahgerd", bornYear: 2012, diedYear: 2015, color: "#eeddcc", text: "ERMAHGERD GERSBERMS", imageUrl: "https://i.imgflip.com/26ae.jpg" },
  { id: "badluckbrian", name: "Bad Luck Brian", bornYear: 2012, diedYear: 2020, color: "#aa88cc", text: "TAKES A PHOTO, BLINKS", imageUrl: "https://i.imgflip.com/1bip.jpg" },
  { id: "doge", name: "Doge", bornYear: 2013, diedYear: 2026, color: "#ffcc66", text: "MUCH WOW SO AMAZING", imageUrl: "https://i.imgflip.com/4t0m5.jpg" },
  { id: "harlemshake", name: "Harlem Shake", bornYear: 2013, diedYear: 2013, color: "#ff3333", text: "AND DO THE HARLEM SHAKE", imageUrl: "https://i.imgflip.com/15nz1f.jpg" },
  { id: "fox", name: "What Does the Fox Say?", bornYear: 2013, diedYear: 2015, color: "#ff7733", text: "RING-DING-DING-DING-DINGERINGEDING", imageUrl: "https://i.imgflip.com/4o7q0.jpg" },
  { id: "thedress", name: "The Dress", bornYear: 2015, diedYear: 2015, color: "#3366cc", text: "BLUE & BLACK or WHITE & GOLD?", imageUrl: "https://i.imgflip.com/i6j00.jpg" },
  { id: "hotlinebling", name: "Hotline Bling", bornYear: 2015, diedYear: 2018, color: "#ff6699", text: "DRAKE DANCING IN LIGHTBOX", imageUrl: "https://i.imgflip.com/30b1gx.jpg" },
  { id: "leftshark", name: "Left Shark", bornYear: 2015, diedYear: 2016, color: "#88ccdd", text: "SUPER BOWL DANCE OUT OF SYNC", imageUrl: "https://i.imgflip.com/h49n2.jpg" },
  { id: "datboi", name: "Dat Boi", bornYear: 2016, diedYear: 2017, color: "#339933", text: "HERE COMES DAT BOI! O SHIT WADUP!", imageUrl: "https://i.imgflip.com/13u0g5.jpg" },
  { id: "ppap", name: "PPAP", bornYear: 2016, diedYear: 2017, color: "#eecc33", text: "PEN-PINEAPPLE-APPLE-PEN", imageUrl: "https://i.imgflip.com/1bbona.jpg" },
  { id: "harambe", name: "Harambe", bornYear: 2016, diedYear: 2018, color: "#555555", text: "DICKSOUT FOR HARAMBE", imageUrl: "https://i.imgflip.com/45jzj6.jpg" },
  { id: "mockingspongebob", name: "Mocking SpongeBob", bornYear: 2017, diedYear: 2019, color: "#ffff33", text: "MoCkiNg SpOnGeBoB", imageUrl: "https://i.imgflip.com/1otk96.jpg" },
  { id: "distractedboyfriend", name: "Distracted Boyfriend", bornYear: 2017, diedYear: 2020, color: "#ff5555", text: "LOOKING AT OTHER OPTION", imageUrl: "https://i.imgflip.com/1ur9b0.jpg" },
  { id: "saltbae", name: "Salt Bae", bornYear: 2017, diedYear: 2019, color: "#eeddcc", text: "SPRINKLING SALT ELEGANTLY", imageUrl: "https://i.imgflip.com/1hj6i2.jpg" },
  { id: "rollsafe", name: "Roll Safe", bornYear: 2017, diedYear: 2019, color: "#444444", text: "CAN'T GET FIRED IF YOU DON'T WORK", imageUrl: "https://i.imgflip.com/1h7in3.jpg" },
  { id: "shootingstars", name: "Shooting Stars", bornYear: 2017, diedYear: 2018, color: "#aa33ff", text: "SPINNING INTO COSMOS", imageUrl: "https://i.imgflip.com/3wzloy.jpg" },
  { id: "steamedhams", name: "Steamed Hams", bornYear: 2018, diedYear: 2020, color: "#eedd99", text: "AURORA BOREALIS IN YOUR KITCHEN", imageUrl: "https://i.imgflip.com/2x09gv.jpg" },
  { id: "ugandanknuckles", name: "Ugandan Knuckles", bornYear: 2018, diedYear: 2019, color: "#ff2244", text: "DO YOU KNOW DE WAY?", imageUrl: "https://i.imgflip.com/229s3f.jpg" },
  { id: "surprisedpikachu", name: "Surprised Pikachu", bornYear: 2018, diedYear: 2022, color: "#ffee33", text: "⊙ ▃ ⊙ SURPRISED PIKACHU", imageUrl: "https://i.imgflip.com/2kbn1e.jpg" },
  { id: "mothlamp", name: "Moth Lamp", bornYear: 2018, diedYear: 2019, color: "#ccccaa", text: "LAMP LÄMP LÖÖP", imageUrl: "https://i.imgflip.com/2iv4z1.jpg" },
  { id: "womanyellingcat", name: "Woman Yelling at a Cat", bornYear: 2019, diedYear: 2022, color: "#ffffff", text: "SMUDGE THE CAT AT TABLE", imageUrl: "https://i.imgflip.com/345v97.jpg" },
  { id: "stonks", name: "Stonks", bornYear: 2017, diedYear: 2023, color: "#33cc88", text: "STONKS ONLY GO UP ↑", imageUrl: "https://i.imgflip.com/3388rw.png" },
  { id: "coffindance", name: "Coffin Dance (Astronomian)", bornYear: 2020, diedYear: 2021, color: "#222222", text: "DANCING PALLBEARERS", imageUrl: "https://i.imgflip.com/3vcsqq.png" },
  { id: "bernie_mittens", name: "Bernie Sanders' Mittens", bornYear: 2021, diedYear: 2021, color: "#888888", text: "ONCE AGAIN I AM ASKING", imageUrl: "https://i.imgflip.com/3oevdk.jpg" },
  { id: "axelinharlem", name: "Axel in Harlem", bornYear: 2023, diedYear: 2023, color: "#ff55aa", text: "ANIMAN STUDIOS", imageUrl: "https://i.imgflip.com/7e1xl2.png" },
  { id: "grimaceshake", name: "Grimace Shake", bornYear: 2023, diedYear: 2023, color: "#8833ff", text: "HAPPY BIRTHDAY GRIMACE", imageUrl: "https://i.imgflip.com/7r5x7a.png" },
  { id: "skibiditoilet", name: "Skibidi Toilet", bornYear: 2023, diedYear: 2026, color: "#777777", text: "SKIBIDI DOP DOP YES YES", imageUrl: "https://i.imgflip.com/7mzkd0.jpg" },
  { id: "mewing", name: "Mewing / Looksmaxxing", bornYear: 2024, diedYear: 2026, color: "#ee88dd", text: "🤫🧏 BYE BYE", imageUrl: "https://i.imgflip.com/8q11dg.png" },
  { id: "hawktuah", name: "Hawk Tuah", bornYear: 2024, diedYear: 2025, color: "#ff8888", text: "SPIT ON THAT THANG", imageUrl: "https://i.imgflip.com/8ufgni.jpg" },
  { id: "chillguy", name: "Chill Guy", bornYear: 2024, diedYear: 2026, color: "#ddaa77", text: "I'M JUST A CHILL GUY", imageUrl: "https://i.imgflip.com/9au02y.jpg" }
];
